-- Allow explicit id on upsert (Admin publishes to id = 1)
ALTER TABLE public.club_settings
  ALTER COLUMN id SET GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO public.club_settings (
  id,
  club_tagline,
  show_tagline,
  location_name,
  latitude,
  longitude,
  logo_url,
  accent_color,
  panel_bg,
  panel_bg_custom,
  bg_photo_url,
  pro_shop_title,
  pro_shop_rows,
  community_items,
  tournament_data,
  display_slots
)
SELECT
  1,
  '18 holes · Est. 1997',
  true,
  'Charlotte, NC',
  35.1653,
  -80.6093,
  'https://xntieyqrodsjelotcmnr.supabase.co/storage/v1/object/public/assets/olde%20sycamore%20golf%20club%20logo.png',
  '#7ab648',
  'dark_green',
  'rgba(6,14,8,0.82)',
  'https://xntieyqrodsjelotcmnr.supabase.co/storage/v1/object/public/assets/img-olde-sycamore-1.webp',
  'Pro Shop & Dining',
  '[]'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb,
  '{}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.club_settings WHERE id = 1);
